linters:
  enable:
    - govet
    - errcheck
    - unused
    - gosimple
    - ineffassign
    - contextcheck
    - dupl
    - errname
    - funlen
    - gocyclo
    - goimports
    
run:
  tests: true
  timeout: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck