// Code generated by mockery v2.43.2. DO NOT EDIT.

package application

import mock "github.com/stretchr/testify/mock"

// MockEventConsumer is an autogenerated mock type for the EventConsumer type
type MockEventConsumer struct {
	mock.Mock
}

// BindBookCreated provides a mock function with given fields: _a0
func (_m *MockEventConsumer) BindBookCreated(_a0 func(*CreatedEvent)) {
	_m.Called(_a0)
}

// Close provides a mock function with given fields:
func (_m *MockEventConsumer) Close() {
	_m.Called()
}

// StartConsuming provides a mock function with given fields:
func (_m *MockEventConsumer) StartConsuming() {
	_m.Called()
}

// NewMockEventConsumer creates a new instance of MockEventConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventConsumer {
	mock := &MockEventConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
