// Code generated by mockery v2.42.3. DO NOT EDIT.

package book

import mock "github.com/stretchr/testify/mock"

// MockBookEventPropagator is an autogenerated mock type for the BookEventPropagator type
type MockBookEventPropagator struct {
	mock.Mock
}

// PropagateBookCreated provides a mock function with given fields: bookCreated
func (_m *MockBookEventPropagator) PropagateBookCreated(bookCreated *BookCreated) {
	_m.Called(bookCreated)
}

// NewMockBookEventPropagator creates a new instance of MockBookEventPropagator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookEventPropagator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookEventPropagator {
	mock := &MockBookEventPropagator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
