basePath: /
definitions:
  book.BookResource:
    properties:
      categories:
        items:
          type: string
        type: array
      description:
        type: string
      id:
        type: string
      name:
        type: string
      publish_date:
        type: string
    type: object
  book.CreateBookRequest:
    properties:
      categories:
        items:
          type: string
        type: array
      description:
        type: string
      name:
        type: string
      publish_date:
        type: string
    required:
    - categories
    - description
    - name
    - publish_date
    type: object
host: localhost:8080
info:
  contact:
    email: mario.calin@mindcurv.com
    name: Mario
    url: http://example.org
  description: API for creating and retreiving books
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Library Api
  version: "1.0"
paths:
  /book:
    get:
      description: get all books that are stored in the system
      operationId: get-all-books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/book.BookResource'
      summary: Get all persisted books
      tags:
      - books
    post:
      consumes:
      - application/json
      description: Creat a book with required parameters
      parameters:
      - description: Book
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/book.CreateBookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/book.BookResource'
      summary: Create a book
      tags:
      - books
swagger: "2.0"
